### ISSUE TITLE
container-job/vm-job failed to run with exit code 126

### ISSUE THREAD

**Issue by arthurkushman** [actions/example-services#10]
By using this example: https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
(not changing anything) getting the error

##[error]Process completed with exit code 126.
Run npm ci
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/__w/buildsqlx/buildsqlx/./postgres\") set in config.json failed: no such file or directory": unknown
##[error]Process completed with exit code 126.

**Comment by arthurkushman** [comment]
![Screen Shot 2019-09-13 at 12 24 22](https://user-images.githubusercontent.com/2669610/64852180-8e3ae500-d621-11e9-9570-ca25d6068ece.png)

**Comment by arthurkushman** [comment]
Basically I just need a PostgreSQL up and running on 127.0.0.1 postgres/postgres on port 5432 to connect from Go code.

**Comment by sarahabd** [comment]
@arthurkushman do you have set `working-directory: ./postgres` on your action?

**Comment by arthurkushman** [comment]
I'm totally not familiar with GitHub Actions, so I don't know where to apply `working-directory: ./postgres` does this should be set in the same file - `postgres-service.yml`? Do you have an example?

**Comment by arthurkushman** [comment]
Yes it is set like this:
```
jobs:
  container-job:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified continer rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  node:10.16-jessie

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
        working-directory: ./postgres
      - run: node client.js
        working-directory: ./postgres
        env:
          # use postgres for the host here because we have specified a container for the job.
          # If we were running the job on the VM this would be localhost
          POSTGRES_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
```

**Comment by arthurkushman** [comment]
After removing working-directory from anywhere got the error:
![Screen Shot 2019-09-13 at 13 42 07](https://user-images.githubusercontent.com/2669610/64857183-86347280-d62c-11e9-9aa6-30954de8e5bd.png)

Yaml config:
```
name: Postgres Service Example

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified continer rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  node:10.16-jessie

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: node client.js
        env:
          # use postgres for the host here because we have specified a container for the job.
          # If we were running the job on the VM this would be localhost
          POSTGRES_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

  # Runs all steps on the VM
  # The service containers will use host port binding instead of container networking so you access them via localhost rather than the service name
  vm-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: node client.js
        env:
          # use localhost for the host here because we have specified a container for the job.
          # If we were running the job on the VM this would be postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
```
What I need is just run PostgreSQL on 127.0.0.1:5432 to be able to connect from Go program, if there is no need for npm I can remove those blocks for ex.
