### ISSUE TITLE
dial tcp 127.0.0.1:5432: connect: connection refused

### ISSUE THREAD

**Issue by arthurkushman** [actions/example-services#22]
Hello, everything worked fine until recently without any changes in configuration files:
```
name: Postgres Service Example

on:
  push:
    branches:
      - master
      - db_postgres_setup
  pull_request:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified continer rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  node:10.16-jessie
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
```

And the service that trying to connect from another container:
```
name: Build and run
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test

    - name: Code coverage
      run: go test -coverprofile=coverage.out

    - name: Push coverage to codecov
      run: bash <(curl -s https://codecov.io/bash) -t 489df204-a660-49b8-8ddb-6637ae4c4216

```

An error message is: 
```
    builder_test.go:53: 
        	Error Trace:	builder_test.go:53
        	Error:      	Received unexpected error:
##[error]        	            	dial tcp 127.0.0.1:5432: connect: connection refused
```

It was exactly the same no changes to the configs and to connection string, just starting to fail.

**Comment by mrturkmen06** [comment]
Hi @arthurkushman 

It might be too late that I am trying to respond to you, but it may help for others who might looking for a solution for that problem. I could not understand the purpose of using node. I hope, following workflow might help to anyone. 

Why do not you prefer to use this one instead ? 

```
name: Build and  Publish Docker
on: [push]

jobs:
  build:
    runs-on:  ubuntu-latest

    services:
      postgres:
        image: postgres:latest 
        env:
          POSTGRES_PASSWORD: dummy-password
          POSTGRES_USER: postgres
          POSTGRES_DB: dummydb
            # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
             dep ensure
          fi

     - name: Build
       run: go build -v .
      
     - name: Test with cover profile
       run: go test -coverprofile=coverage.out -v --race ./...

    - name: Push coverage to codecov
      run: bash <(curl -s https://codecov.io/bash) -t 489df204-a660-49b8-8ddb-6637ae4c4216

```
