### ISSUE TITLE
Provide native seeding capability for actions

### ISSUE THREAD

**Issue by jonny7** [actions/example-services#23]
I had already asked support and they said native seeding isn't available and to check the actions forum. I posted this question (https://github.community/t5/GitHub-Actions/Support-for-seeding-database/m-p/53702#M8933) and it was suggested I create an issue for this here.

In many pipelines it can be beneficial to run a small set of database tests. Docker provides the ability to natively seed a database like so:
```
psql:
    image: "postgres"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql
```
Would it be possible to have some kind of native action for this? Or if not, an acceptable workaround documented? I did check the docs some time ago but couldn't find any information on seeding. But I may have missed that

Thanks 😄
