### ISSUE TITLE
Actions and services feedback (health check questions)

### ISSUE THREAD

**Issue by dentarg** [actions/example-services#3]
Hi @chrispat and @mscoutermarsh 👋 

As you have been active on this repo, I assume you have some insight in the services side of GitHub Actions. I hope you don't mind receiving some feedback here. I thought it would be quicker to reach the right people than going via support@github.com.

I'm thankful for the [postgres example](https://github.com/actions/example-services/blob/dfd84e0637dda63c0359a07a7161fbfd2a6da738/.github/workflows/postgres-service.yml) as it brought up a few things that aren't [in the docs](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idservices) (yet?): ports get randomly assigned (this is mentioned but I think I overlooked it as `${{ job.services.redis.ports['6379'] }}` wasn't used in the YAML snippet) and that health checks are needed.

About the health checks, my tests need Memcached and RabbitMQ, and I've been successful in starting memcached, but not RabbitMQ.

Here's the `services` definition of my job:

```yaml
    services:
      memcached:
        image: memcached:latest
        ports:
        - 11211/udp
        # needed because the memcached container does not provide a healthcheck
        options: --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'" --health-interval 10s --health-timeout 5s --health-retries 5
      rabbitmq:
        image: rabbitmq:latest
        ports:
        - 5672/tcp
        # needed because the rabbitmq container does not provide a healthcheck
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5
```

It looks like the container needs to report healthy in ~30 seconds (the other time I ran this it said "waiting 32 seconds ..."):

```
starting
rabbitmq service is starting, waiting 29 seconds before checking again.
/usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 9d446afa3d021ab0c08c48fd699119a452a109783c1c2032862cc813562b7474
unhealthy
##[error]Failed to initialize, rabbitmq service is unhealthy.
```

I'm not sure why it isn't reporting healthy, it works locally for me, in less than 30 seconds. Maybe my computer is faster than GitHub's? :-)

Is it possible for GitHub Actions to give me more info on what's happening? Like `docker inspect --format='{{json .State.Health}}'`
